KeyError: 'source_documents'

File "C:\Users\Public\GroupB\Memory RAG Chatbot\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
File "C:\Users\Public\GroupB\Memory RAG Chatbot\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Public\GroupB\Memory RAG Chatbot\app.py", line 79, in <module>
    for doc in result["source_documents"]:
               ~~~~~~^^^^^^^^^^^^^^^^^^^^
